/** @file config.h
 * @brief Header file for compile time settings
 *
 * @warning Recompile entire code whenever you make any changes to this file:
 @code
   make; make clean
 @endcode
 */

/* Edit the following to save (some_ paths generated by the
   single level method to disk */

/* Save paths from? */
//#define SAVE_PATHS 1

/* First path to save */
#define SAVE_FIRST_PATH 5000

/* Last path to save */
#define SAVE_LAST_PATH 5100

/* Log QoI in singlelevel method? */
//#define LOG_QOI 1
